# Generated by Django 2.1.1 on 2018-09-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickstarter',
            name='campaign_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
