version: '3'

services:
    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always

    web:
        env_file: .env
        build: ./web
        container_name: 'kickstarter_web'
        command: ./entrypoint.sh
        volumes:
            - ./web:/src
        ports:
            - '8000:8000'
        depends_on:
            - db
        restart: always

volumes:
    postgres_data:
